### ISSUE TITLE
Running as windows service -> no window control

### ISSUE THREAD

**Issue by normen** [Krombik/keysender#1]
Hi,

first of all thanks for this software, its very exhaustive and works very well for me.

However I noticed that when I run my node application as a windows service I don't seem to have access to the application windows anymore. For all I know I am running my service as that same user which is also an admin.

I don't know if this is intended behavior or if its simply not possible to control the UI from a service this way but I thought I would mention this.

Cheers,
Normen Hansen

**Comment by Krombik** [comment]
Hi, this library use WinAPI, so I gues it can't be fixed.

**Comment by normen** [comment]
Okay, thanks for the quick reply, no problem.
