### ISSUE TITLE
`moveTo` is not working on virtual window

### ISSUE THREAD

**Issue by tuliocastro** [Krombik/keysender#12]
Hey, I wanna start saying this is a really nice library,  I was doing some tests with the virtual window and it seems the moveTo doesn't work as documented. Basically I wanna do an auto click for background windows. The click seems to working perfectly, but it only clicks wherever my mouse is point. It is not really moving and then click. Is it a limitation or it might be an issue?

I was trying with this simple code
```javascript
import keysender from 'keysender';
const { Hardware, Virtual} = keysender;

const hardware = new Hardware("Notepad");
const virtual = new Virtual("Notepad"); 

await virtual.mouse.moveTo(100,100); // doesnt do anything
await virtual.mouse.click();
```
Thank you very much, hope to hear from you.

**Comment by Krombik** [comment]
Some virtual methods can not work in some windows, it mationed in readme https://github.com/Krombik/keysender#hardware-or-virtual (see Note section)

**Comment by Krombik** [comment]
You can try to find window children, which receive mouse move messages
