### ISSUE TITLE
disableInput keyboard keys

### ISSUE THREAD

**Issue by ch3rn1k** [Krombik/keysender#14]
Thanks for new ability, but someting is wrong.
`disableInput(true, { keyboard: ['a'] });` not blocking `a` key

**Comment by Krombik** [comment]
should be fixed in 2.2.1

**Comment by ch3rn1k** [comment]
Looks like still no :(

Am I right - code `disableInput(true, { keyboard: ['a'] });` should block `a` and all others should work?

**Comment by Krombik** [comment]
Yes, I tested, it's works

**Comment by ch3rn1k** [comment]
> Yes, I tested, it's works

Ty, forgot to rebuild my app, work fine now
