### ISSUE TITLE
Question/Suggestion: Ability to pass through GlobalHotkey key (Side effects only)

### ISSUE THREAD

**Issue by nfour** [Krombik/keysender#2]
Hi!

I'd like to be able to, on pressing `a` trigger an action as a side effect, however, I'd like `a` to come through as normal.

Is there a way to do this?

**Comment by Krombik** [comment]
No, [here you can find why](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerhotkey#remarks), but you can try sendKey('a') method from Virtual module, but not all windows support it.

**Comment by nfour** [comment]
Thanks, that is too bad.

My use case is macros for a video game - I use AHK , but it tends to grow in difficulty when building more complex async control flow.

**Comment by Krombik** [comment]
@nfour from 2.1.0 it is possible by using `LowLevelHook` class
