### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by nnguyen01** [Krombik/keysender#24]
Getting access denied from this package after bundling an electron application. Do I need administrator access to use keysender?

![354226219_156269080799043_7527330664212610613_n](https://github.com/Krombik/keysender/assets/24705681/34ebf307-293f-49cc-a106-ec1c16d4d13f)

**Comment by Krombik** [comment]
Can't tell, try using it with an admin account, if the error still comes up, it might be a build issue.

**Comment by nnguyen01** [comment]
![image](https://github.com/Krombik/keysender/assets/24705681/ba441b1b-424f-4c2d-949a-5316fcf02810)

Yea looks like bitdefender is detecting this package as a virus

**Comment by Krombik** [comment]
Hmmm, windows defender is ok with it, but it can control mouse, keyboard, applications and do screenshots, so it can be detected as malware)
