### ISSUE TITLE
Could you add support of capturing screenshot in png or bmp format?

### ISSUE THREAD

**Issue by huangwb68** [Krombik/keysender#32]
I want to perform OCR on the screenshot to get the words so that I can determine whether to click on it.  The function workwindow.capture() returns an RGBA raw buffer,  but the OCR engines such as Tesseract.js only support formats of png, jpg, bmp, and pbm.

**Comment by adrianostanley** [comment]
@huangwb68 did you find any solutions to that?

I believe I'm in a earlier step where I have no idea how to handle the **RGBA raw buffer**. Are you able to save that buffer in any way to a file?

**Comment by huangwb68** [comment]
> @huangwb68 did you find any solutions to that?
> 
> I believe I'm in a earlier step where I have no idea how to handle the **RGBA raw buffer**. Are you able to save that buffer in any way to a file?

I switched to use robotjs instead.

**Comment by Krombik** [comment]
capture can return `rgba` data, check [documentation](https://github.com/Krombik/keysender?tab=readme-ov-file#capture)
