### ISSUE TITLE
do you have an plan to refactor without node-gyp

### ISSUE THREAD

**Issue by YMC-GitHub** [Krombik/keysender#33]
thank you for your sharing. this repo help me a lot.

without node-gyp , like [LaunchMenu/node-global-key-listener](https://github.com/LaunchMenu/node-global-key-listener)

or refactor with rust.

it may be good to refactor this. but i am newer on cpp.

**Comment by Krombik** [comment]
Currently i have no windows machine, so i can't do anything with this repo

**Comment by YMC-GitHub** [comment]
could you give me some help about capturing active window(not screen) or workwindow in cpp or rust?

**Comment by Krombik** [comment]
and [this line](https://github.com/Krombik/keysender/blob/master/src/addon/workwindow.cpp#L116) is also very important

**Comment by YMC-GitHub** [comment]
thanks for your reply.
