### ISSUE TITLE
Ability to use Double Quotes (") in sendKey?

### ISSUE THREAD

**Issue by Smigg-y** [Krombik/keysender#34]
AFAIK the KeyCode for double and single quotes are the exact same (222) which is an issue for me as for my use-case I need double quotes. Whilst I could do `["Shift", "'"]` to get a double quote, it is dependant on the end users keyboard layout as to whether it'll give " or @ etc.

Is there a way to do this or is it possible to implement?

**Comment by Krombik** [comment]
sendKey method is for sending keys, not for typing
