### ISSUE TITLE
Save image with sharp

### ISSUE THREAD

**Issue by ch3rn1k** [Krombik/keysender#6]
Hello! Awesome lib, thank you! Can you tell me how can I save `capture()` with `sharp`?
Everytime I'm getting black image...

```js
import sharp from 'sharp';
import { Hardware } from 'keysender';

const desktop = new Hardware(0);

const saver = () => {
  const screen = desktop.workwindow.capture();
  sharp(screen.data, {
    raw: {
      width: screen.width,
      height: screen.height,
      channels: 4
    }
  }).toFile(...);
};

saver();
```

![Screenshoot 1664009799183](https://user-images.githubusercontent.com/19375789/192089519-3b749411-a4c5-4dbf-9a5d-24261d576a7d.png)
![Screenshoot 1664009808044](https://user-images.githubusercontent.com/19375789/192089521-799939db-7922-4058-a8cb-8f686f014227.png)

**Comment by ch3rn1k** [comment]
Looks like problem in `capture()`, it returns to me strange things:

![image](https://user-images.githubusercontent.com/19375789/192089937-7c2d763d-2401-4cb0-bd57-9c45e022b09c.png)

**Comment by ch3rn1k** [comment]
Found that problem with `const desktop = new Hardware(0);`. When using 0 it always black, but if I set something like `const desktop = new Hardware('Windows.UI.Core.CoreWindow');` it works fine. How can i fix using zero? Thanks

**Comment by Krombik** [comment]
use just `const desktop = new Hardware();`

**Comment by ch3rn1k** [comment]
> use just `const desktop = new Hardware();`

Well yea, that works, thanks!
