### ISSUE TITLE
Cancel/Interrupt an action

### ISSUE THREAD

**Issue by ch3rn1k** [Krombik/keysender#8]
Hello! Any way to interrupt an action? Like [printText](https://github.com/Krombik/keysender#printtext) or [humanMoveTo](https://github.com/Krombik/keysender#humanmoveto)? Thanks

**Comment by Krombik** [comment]
not currently, but I can add an extra parameter, a validation function that will be called before every mouse move or print, or I can try to add `ref` parameter to which the cancel method will be written

**Comment by ch3rn1k** [comment]
Yeah, that would be great

**Comment by Krombik** [comment]
I add `cancelCurrent` method to sendKeys, printText and humanMoveTo methods, call it to interrupt the execution

**Comment by ch3rn1k** [comment]
Works great! Thanks! :)
