### ISSUE TITLE
Any way to wait for a key

### ISSUE THREAD

**Issue by ch3rn1k** [Krombik/keysender#9]
Hey ya, any way to add a function like to wait for a key press?
Smth like `waitKey`,  `waitClick`, `waitMove`, `waitScroll`

Dat will be awesome <3

**Comment by Krombik** [comment]
if you mean pressing a key outside of keysender - it's not possible, winapi doesn't have methods for that

**Comment by ch3rn1k** [comment]
> if you mean pressing a key outside of keysender - it's not possible, winapi doesn't have methods for that

I mean to make a wait function, you already have `GlobalHotkey` that detects key press

**Comment by ch3rn1k** [comment]
Like `await obj.keyboard.waitKey("a");`

**Comment by Krombik** [comment]
in 2.1.0 the `LowLevelHook` class was added with which this logic can be implemented

**Comment by ch3rn1k** [comment]
> in 2.1.0 the `LowLevelHook` class was added with which this logic can be implemented

Nice one, thanks, but is there a way to use `async/await` with `LowLevelHook.on()`?
Like `await LowLevelHook.on('keyboard', 'a', true)`

**Comment by Krombik** [comment]
no, it works like addEventListener in browser

**Comment by ch3rn1k** [comment]
well, still awesome lib, hope you will implement `async/await` later

**Comment by ch3rn1k** [comment]
> but you can write something like whis
> 
> ```js
> const waitForKey = (device, button, state) =>
>   new Promise((resolve) => {
>     const unlisten = LowLevelHook.on(device, button, state, () => {
>       unlisten();
> 
>       resolve();
>     });
>   });
> ```

Looks like after unlistening next time `.on` aint works

**Comment by Krombik** [comment]
thats what unlisten do

**Comment by ch3rn1k** [comment]
> thats what unlisten do

I mean another call in new function with `waitForKey` ain't works. I can only 1 single time call `waitForKey` in a code

**Comment by ch3rn1k** [comment]
If we talking about `addEventListener` it can be added and removed. In another function I can call `addEventListener` again and it will work

**Comment by ch3rn1k** [comment]
After calling `LowLevelHook.deleteAll();` it can be called again

**Comment by Krombik** [comment]
should be fixed in 2.1.1

**Comment by ch3rn1k** [comment]
> should be fixed in 2.1.1

Thanks

**Comment by ch3rn1k** [comment]
Is there a way to listen keys combination? 
`["ctrl", "e"]`

**Comment by Krombik** [comment]
no, but you can do it by yourself
